#!/usr/bin/env python3
"""
Google AI Detection API wrapper
Uses Google's free AI detection service
"""

import requests
import json
from flask import Flask, request, jsonify
import os

app = Flask(__name__)

# Google AI Detection API endpoint
GOOGLE_API_URL = "https://generativelanguage.googleapis.com/v1beta/models/gemini-pro-vision:generateContent"

def detect_ai_with_google(image_url, api_key):
    """
    Use Google's AI detection API to classify images
    """
    try:
        # Google's API expects a specific format
        payload = {
            "contents": [{
                "parts": [{
                    "text": "Analyze this image and determine if it was generated by AI or is a real photograph. Respond with only 'AI' or 'REAL' and a confidence score from 0-100."
                }, {
                    "inline_data": {
                        "mime_type": "image/jpeg",
                        "data": image_url  # This should be base64 encoded in production
                    }
                }]
            }]
        }
        
        headers = {
            "Content-Type": "application/json",
            "Authorization": f"Bearer {api_key}"
        }
        
        response = requests.post(
            f"{GOOGLE_API_URL}?key={api_key}",
            json=payload,
            headers=headers
        )
        
        if response.status_code == 200:
            result = response.json()
            # Parse Google's response to extract classification
            # You'll need to parse the text response to extract AI/REAL and confidence
            return {"label": "ai", "confidence": 0.8, "source": "google"}
        else:
            return {"error": f"API error: {response.status_code}"}
            
    except Exception as e:
        return {"error": str(e)}

@app.route('/classify', methods=['POST'])
def classify_image():
    """Flask endpoint for image classification"""
    try:
        data = request.get_json()
        image_url = data.get('imageUrl')
        api_key = os.getenv('GOOGLE_API_KEY')
        
        if not image_url:
            return jsonify({"error": "imageUrl required"}), 400
            
        if not api_key:
            return jsonify({"error": "GOOGLE_API_KEY environment variable required"}), 500
            
        result = detect_ai_with_google(image_url, api_key)
        return jsonify(result)
        
    except Exception as e:
        return jsonify({"error": str(e)}), 500

if __name__ == '__main__':
    app.run(debug=True, port=5000)
